# Generated by Django 5.2.4 on 2025-08-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('fio', models.CharField(blank=True, help_text='Введите ФИО', max_length=150, null=True,
                                         verbose_name='ФИО')),
                ('comment', models.TextField(default='отсутствует', help_text='Введите комментарий',
                                             verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите владельца получателя', null=True,
                                            on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                            verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['owner', 'email', 'fio'],
            },
        ),
    ]
