# Generated by Django 5.2.4 on 2025-08-15 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, help_text='Укажите дату и время первой отправки', null=True, verbose_name='Дата и время первой отправки')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Укажите дату и время первой отправки', null=True, verbose_name='Дата и время первой отправки')),
                ('letter', models.ForeignKey(help_text='Укажите сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, to='mailer.letter', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(help_text='Укажите владельца рассылки', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('recipients', models.ManyToManyField(help_text='Укажите получателей рассылки', related_name='mailings', to='mailer.recipient', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status', 'owner', 'started_at', 'finished_at'],
            },
        ),
    ]
