# Generated by Django 5.2.4 on 2025-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_mailing_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Укажите дату и время завершения отправки',
                                       null=True, verbose_name='Дата и время завершения отправки'),
        ),
    ]
