# Generated by Django 5.2.4 on 2025-09-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_mailing_finished_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('successfully', 'Успешно'), ('unsuccessfully', 'Не успешно')], max_length=40)),
                ('date_time', models.DateTimeField(blank=True, help_text='Укажите дату и время попытки', null=True, verbose_name='Дата и время попытки')),
                ('mail_server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(help_text='Укажите рассылку', on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['mailing', 'status', 'date_time'],
            },
        ),
    ]
