# Generated by Django 5.2.4 on 2025-09-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(help_text='Укажите рассылку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.mailing', verbose_name='Рассылка'),
        ),
    ]
