# Generated by Django 5.2.4 on 2025-10-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_toggle_user_active',
                                      'Может блокировать/разблокировать пользователя')],
                     'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
